package com.cuzz.rookiecrates.model;

public class DCrateLootWithBLOBs extends DCrateLoot {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rookie_crate_loot.loot_itemstack_base64
     *
     * @mbggenerated Wed May 07 18:09:00 CST 2025
     */
    private String lootItemstackBase64;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rookie_crate_loot.lores
     *
     * @mbggenerated Wed May 07 18:09:00 CST 2025
     */
    private String lores;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rookie_crate_loot.description
     *
     * @mbggenerated Wed May 07 18:09:00 CST 2025
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rookie_crate_loot.loot_itemstack_base64
     *
     * @return the value of rookie_crate_loot.loot_itemstack_base64
     *
     * @mbggenerated Wed May 07 18:09:00 CST 2025
     */
    public String getLootItemstackBase64() {
        return lootItemstackBase64;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rookie_crate_loot.loot_itemstack_base64
     *
     * @param lootItemstackBase64 the value for rookie_crate_loot.loot_itemstack_base64
     *
     * @mbggenerated Wed May 07 18:09:00 CST 2025
     */
    public void setLootItemstackBase64(String lootItemstackBase64) {
        this.lootItemstackBase64 = lootItemstackBase64 == null ? null : lootItemstackBase64.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rookie_crate_loot.lores
     *
     * @return the value of rookie_crate_loot.lores
     *
     * @mbggenerated Wed May 07 18:09:00 CST 2025
     */
    public String getLores() {
        return lores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rookie_crate_loot.lores
     *
     * @param lores the value for rookie_crate_loot.lores
     *
     * @mbggenerated Wed May 07 18:09:00 CST 2025
     */
    public void setLores(String lores) {
        this.lores = lores == null ? null : lores.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rookie_crate_loot.description
     *
     * @return the value of rookie_crate_loot.description
     *
     * @mbggenerated Wed May 07 18:09:00 CST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rookie_crate_loot.description
     *
     * @param description the value for rookie_crate_loot.description
     *
     * @mbggenerated Wed May 07 18:09:00 CST 2025
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}